services:
  - type: web
    name: college-leave-flow
    env: node
    plan: free
    autoDeploy: true
    buildCommand: npm ci && npm run build && npm prune --production
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
